services:
  - type: web
    name: ivr-clinical-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app_backend:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.11.9
